AutoSolution/Auto/Controllers/AutoController.cs
using Microsoft.AspNet.Identity;
using Models.DataViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Auto.Controllers
{
    public class AutoController : Controller
    {
        static HttpClient client = new HttpClient();
        string BaseURL = ConfigurationManager.AppSettings["autoService"];
        public ActionResult Index()
        {
            try
            {
                HttpResponseMessage response = client.GetAsync($"{BaseURL}/GetAllPackage").Result;
                List<PackageDTO> ct = new List<PackageDTO>();
                if (response.IsSuccessStatusCode)
                {
                    ct = JsonConvert.DeserializeObject<List<PackageDTO>>(response.Content.ReadAsStringAsync().Result);
                }
                return View(ct);
            }
            catch (Exception ex)
            {
                return new HttpNotFoundResult();
            }
        }

        public ActionResult AddPack()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddPack(PackageDTO pack)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("მონაცემები არავალიდურია!");

                string output = JsonConvert.SerializeObject(pack);
                var stringContent = new StringContent(output, Encoding.UTF8, "application/json");

                HttpResponseMessage response = client.PostAsync($"{BaseURL}/AddPackage", stringContent).Result;

                if (!response.IsSuccessStatusCode)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "დამატების დროს მოხდა შეცდომა. ბოდიშს გიხდით";
                return View();
            }
        }

        public ActionResult PackDetails(string packName)
        {
            try
            {
                if (packName.Equals(""))
                    throw new Exception("მონაცემები არავალიდურია!");

                HttpResponseMessage response = client.GetAsync($"{BaseURL}/GetPackage/{packName}").Result;
                PackageDTO ct = new PackageDTO();
                if (response.IsSuccessStatusCode)
                {
                    ct = JsonConvert.DeserializeObject<PackageDTO>(response.Content.ReadAsStringAsync().Result);
                }
                return View(ct);
            }
            catch (Exception ex)
            {
                return new HttpNotFoundResult();
            }
        }
        public ActionResult DeletePack(string packName)
        {
            try
            {
                if (packName.Equals(""))
                    throw new Exception("მონაცემები არავალიდურია!");

                HttpResponseMessage response = client.GetAsync($"{BaseURL}/GetPackage/{packName}").Result;
                PackageDTO ct = new PackageDTO();
                if (response.IsSuccessStatusCode)
                {
                    ct = JsonConvert.DeserializeObject<PackageDTO>(response.Content.ReadAsStringAsync().Result);
                }
                return View(ct);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        [ValidateAntiForgeryToken]
        [HttpDelete]
        public ActionResult DeletePack(string packName, FormCollection collection)
        {
            try
            {
                HttpResponseMessage response = client.DeleteAsync($"{BaseURL}/DeletePackage/{packName}").Result;

                if (!response.IsSuccessStatusCode)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public ActionResult UserOrder()
        {
            try
            {
                string user = User.Identity.GetUserName().Substring(0, User.Identity.GetUserName().IndexOf("@"));
                HttpResponseMessage response = client.GetAsync($"{BaseURL}/GetOrder/{user}").Result;
                OrderDTO ct = new OrderDTO();
                if (response.IsSuccessStatusCode)
                {
                    ct = JsonConvert.DeserializeObject<OrderDTO>(response.Content.ReadAsStringAsync().Result);
                }
                return View(ct);
            }
            catch (Exception ex)
            {
                return new HttpNotFoundResult();
            }
        }

        public ActionResult BuyPack(string packName)
        {
            try
            {
                string user = User.Identity.GetUserName().Substring(0, User.Identity.GetUserName().IndexOf("@"));
                HttpResponseMessage response = client.GetAsync($"{BaseURL}/AddOrder/{user}/{packName}").Result;
                if (!response.IsSuccessStatusCode)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                }
                return RedirectToAction("UserOrder");
            }
            catch (Exception ex)
            {
                return new HttpNotFoundResult();
            }
        }

        [HttpGet]
        [ChildActionOnly]
        public PartialViewResult UserPacks()
        {
            string user = User.Identity.GetUserName().Substring(0, User.Identity.GetUserName().IndexOf("@"));
            HttpResponseMessage response = client.GetAsync($"{BaseURL}/GetOrderDetails/{user}").Result;
            List<OrderDetailDTO> ct = new List<OrderDetailDTO>();
            if (response.IsSuccessStatusCode)
            {
                ct = JsonConvert.DeserializeObject<List<OrderDetailDTO>>(response.Content.ReadAsStringAsync().Result);
            }
            return PartialView("_UserPacksPartial", ct);

        }
    }
}

AutoSolution/Auto/Views/Auto/AddPack.cshtml
@model Models.DataViewModels.PackageDTO

@{
    ViewBag.Title = "AddPack";
}

<h2>Add Package</h2>

@Html.ViewBag.ErrorMessage

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PackageDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pack_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pack_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pack_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoSolution/Auto/Views/Auto/DeletePack.cshtml
@model Models.DataViewModels.PackageDTO

@{
    ViewBag.Title = "DeletePack";
}

<h2>DeletePack</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PackageDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pack_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pack_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AutoSolution/Auto/Views/Auto/Index.cshtml
@model IEnumerable<Models.DataViewModels.PackageDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Insurance Packages</h2>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "AddPack")
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Pack_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pack_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.ActionLink("Details", "PackDetails", new { packName = item.Pack_Name }) |
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Delete", "DeletePack", new { packName = item.Pack_Name })
                }

            </td>
            @if (Request.IsAuthenticated)
            {
                <td>
                    @Html.ActionLink("Buy", "BuyPack", new { packName = item.Pack_Name }) 
                </td>
            }
        </tr >
    }

</table>

AutoSolution/Auto/Views/Auto/PackDetails.cshtml
@model Models.DataViewModels.PackageDTO

@{
    ViewBag.Title = "PackDetails";
}

<h2>Pack Details</h2>

<div>
    <h4>PackageDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pack_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pack_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

AutoSolution/Auto/Views/Auto/UserOrder.cshtml
@model Models.DataViewModels.OrderDTO

@{
    ViewBag.Title = "UserOrder";
}

<h2>UserOrder</h2>

<div>
    <h4>OrderDTO</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Client)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

    </dl>
    <div style="margin-left:30px">
        @{
            Html.RenderAction("UserPacks", "Auto");
        }
    </div>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

AutoSolution/Auto/Views/Auto/_UserPacksPartial.cshtml
@model IEnumerable<Models.DataViewModels.OrderDetailDTO>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Pack_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Pack_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Details", "PackDetails", new {  packName=item.Pack_name }) |
            @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
        </td>
    </tr>
}

</table>